# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f398ff905d6a7d2579514f15351e6d74bda66bf2ae08b3607dc0ca99d099560c6c0b298d06bfeb95cafc44756d7a2416cf94f8ab4db98c5570f8f9dcde4cc56b

test:
  secret_key_base: 8633a69b11350095159616438bdc2458a236fc99e0133b930010d9ec3b0831227e6f5320f502e5e153a55187f14f1c7fa74777648e761453c0292231281cfff3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
